### PR TITLE
chemiscope documentation

### LINKED ISSUE #758: Add chemiscope to the list of engines that can use metatensor models
Now that https://github.com/lab-cosmo/chemiscope/pull/357 is fully released, we should add a page about chemiscope in the "engines" section of the documentation: https://docs.metatensor.org/latest/atomistic/engines/, with a link back to the chemiscope documentation and a short explanation of what the code does.

### PR DESCRIPTION
**Pull request by sandrasaade**
fixes #758 

----
 📚 [Download documentation preview for this pull-request](https://nightly.link/metatensor/metatensor/actions/artifacts/2104946115.zip)

### CODE REVIEW

**Review by Luthaf — COMMENTED** [review]
This looks good! Could you also add a link to the `chemiscope` engine in the `features` output documentation? Let me know if you don't find the file for this!

**Comment by sandrasaade** [comment]
Hi Guillaume,


Yes, I am doing it in a second.


Sandra

________________________________

**Comment by sandrasaade** [comment]
It should now be sorted.


Sandra

________________________________

**Review by Luthaf — APPROVED** [review]
Looks good, thanks a lot @sandrasaade! I'll merge once CI is happy.

**Comment by sandrasaade** [comment]
Dear Guillaume,


Thanks a lot Guillaume! Even if it is not much at all, it feels like an accomplishment!

I am looking forward to the next hackathon!


Best wishes,

Sandra

________________________________

**Pull request merged**
